### ISSUE TITLE
Farm Opportunity Listing Creation

### ISSUE THREAD

**Issue by lionelmann** [hypenotic/flink#20]
When you sign in as a Farm Opportunity it is not clear that you need to make your account active to be able to create a listing (there is a clear line detailing becoming “active” as a Farm Seeker).
EDIT the line under “Account Status” so that it now reads: “Please make your account active to create your farm opportunity listing. If you are pausing your account, you will also need to unpublish your listing.”

**Comment by lionelmann** [comment]
to review UI and language around this

**Comment by emdecr** [comment]
Closed by commit : https://github.com/hypenotic/flink/commit/c65d64301ea9d85c2a78f3f6c19ce9b6e572aaa2
